<?php

/**
 * Implements hook_preprocess_html
 */
function algolia_search_interface_preprocess_html(&$variables) {

  //get algolia settings
  $algolia_settings = \Drupal::state()->get('algolia_settings');

  //attach algolia settings in js
  $variables['#attached']['drupalSettings']['algolia']['config']['indexname'] = $algolia_settings['indexname'];
  $variables['#attached']['drupalSettings']['algolia']['config']['appId'] = $algolia_settings['appId'];
  $variables['#attached']['drupalSettings']['algolia']['config']['apiKey'] = $algolia_settings['apiKey'];

}

/**
 * Implements hook_theme
 */
function algolia_search_interface_theme($existing, $type, $theme, $path){
  return [
    'instantsearchblock' => [],
  ];
}